#!/usr/bin/env node
const { spawn } = require('child_process')

const PACKAGES = ['common', 'query']

PACKAGES.forEach(package => {
  spawn(
    'yarn',
    [
      'esbuild',
      `./packages/${package}/index.ts`,
      `--outfile=./dist/${package}/index.js`,
      '--bundle',
      '--platform=node',
      '--minify',
      '--tsconfig=tsconfig.build.json',
    ],
    { stdio: 'inherit' },
  )
})
